name = "next-auth-postgres"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-07-01"

[vars]
JWT_SECRET = "your-secret-key"
DATABASE_URL = "postgresql://postgres:Pushkar%40123%23@db.yaiwzbuiqlhlstyeqako.supabase.co:5432/postgres"
